### ISSUE TITLE
Error after killing all redis enterprise pods in Openshift 3.11

### ISSUE THREAD

**Issue by yasser583** [RedisLabs/redis-enterprise-k8s-docs#81]
I have 3 pods running fine, both the bootstrapper and redis enterprise containers are good, I'm using the latest version of the operator so far (5.4.6-1183). After killing all the redis enterprise pods, redis-enterprise-0 pod is unable to get back to life, the redis container is OK but the bootstrapper, causing the pod to fail and of course preventing the other pods to start. This is the error I get from the bootstrapper container:

level=info msg="Waiting for Redis Enterprise API to be accessible"
level=info msg="Redis Enterprise API is accessible"
level=info msg="All pods perform join_cluster"
level=error msg="Bulletin Board says to join cluster but no pods are ready"

If I only kill 1 pod it's able to run again but what I'm testing is the loss of all of them.

**Comment by amiramm** [comment]
Hi @yasser583,
Since you've killed all the pods the REC lost quorum. 
The appropriate next step would be to initialize cluster recovery: 
`kubectl patch rec <cluster-name> --type merge --patch '{"spec":{"clusterRecovery":true}}'`

You can also refer to this article for more info: https://docs.redislabs.com/latest/platforms/kubernetes/cluster-recovery/

Thanks,
Amiram.
